---
title: "GlobalGratitude_LabSpecificData"
output: html_document
editor_options: 
  chunk_output_type: console
---

This codebook is used to generate datasets for each lab to inspect after they complete data collection.

05/10: For now, we'll leave this empty; just in case we have enough time for labs to collect more data
```{r}
# set up packages
library(dplyr)
library(tidyverse)
library(here)
library(openxlsx)
library(readr)

```

# Open data
```{r}
# fetch the main survey data
i_am("code/GlobalGratitude_LabSpecificData.Rmd")

#this is not working for some reason
data <- readRDS(file = here("data", "GlobalGratitude_Final_Cleaned.Rds"))

#edit dataset to only include certain columns
lab_specific_data <- data %>% select(Progress:Duration..in.seconds.,ResponseId,consent:grat_god_letter, me_attention, meals_attention, attention_check:feedback, lab)

```

#Create singular Excel workbook with each lab as an individual sheet
```{r}
# split data by lab
lab_data <- split(lab_specific_data, lab_specific_data$lab)

# create a new workbook
wb <- createWorkbook()

# loop through each lab and write the data to separate sheets
for (lab in names(lab_data)) {
  # add a sheet for each lab
  addWorksheet(wb, lab)
  
  # write the data for the current lab into the sheet
  writeData(wb, sheet = lab, lab_data[[lab]])
}

# save the workbook to an Excel file
saveWorkbook(wb, "lab_specific_data.xlsx", overwrite = TRUE)

```
