---
title: "CrossCulturalMods"
author: "Nicholas A. Coles, Annabel V. Dang"
description: "Organizes all cross-cultural moderator data"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Load packages
```{r}
# install packages
source("setup.R")
```

#Organize cross-cultural mods
```{r}
# main data iso
DF_main <-
  readRDS(file = here(
    "data/final-data",
    "globalgratitude_final_cleaned.Rds"
  ))

DF_main <- DF_main %>%
  mutate(iso = str_sub(lab, 1, 3)) %>%
  filter(!is.na(iso))

sampled <- unique(DF_main$iso)

# cultural distance
DF_culture <- read.csv(here(
  "data/cross-cultural",
  "culturaldistance_combined.csv"
)) %>%
  select(Name, United.States1981.2014) %>%
  rename(
    country = Name,
    dist.us = United.States1981.2014
  ) %>%
  mutate(
    country = str_remove_all(country, "[:digit:]"),
    country = str_remove_all(country, "-")
  ) %>%
  mutate(country = ifelse(country == "Great Britain", "United Kingdom", country)) %>%
  mutate(iso = countrycode(country,
    origin = "country.name",
    destination = "iso3c"
  ))

# relational mobility
DF_relation <- read.csv(file = here(
  "data/cross-cultural",
  "relationalmobility.csv"
)) %>%
  rename("country" = "COUNTRY") %>%
  rename("relational_mobility" = "RMOBLM") %>%
  mutate(country = ifelse(country == "USA", "United States", country)) %>%
  mutate(iso = countrycode(country,
    origin = "country.name",
    destination = "iso3c"
  )) %>%
  select(iso, country, relational_mobility)

# responsibilism
DF_respon <- read.csv(file = here(
  "data/cross-cultural",
  "responsibilism_simulated.csv"
)) %>%
  rename("country" = "Culture") %>%
  rename("responsibilism" = "Responsibilism") %>%
  select(country:responsibilism) %>%
  filter(
    country != "",
    country != "Total"
  ) %>%
  mutate(iso = countrycode(country,
    origin = "country.name",
    destination = "iso3c"
  )) %>%
  mutate(country = ifelse(country == "UK", "United Kingdom", country)) %>%
  mutate(country = ifelse(country == "Macedonia", "North Macedonia", country))

# GDP
DF_GDP <- read.csv(file = here(
  "data/cross-cultural",
  "GDPpc.csv"
)) %>%
  rename("iso" = "Country.Code") %>%
  select(iso, X2011:X2020) %>%
  mutate(country = countrycode(iso,
    origin = "iso3c",
    destination = "country.name"
  )) %>%
  mutate(mean_GDP = rowMeans(select(., X2011:X2020), na.rm = TRUE)) %>%
  select(iso, country, mean_GDP) %>%
  filter(country != "NA")

# tightness-looseness
DF_tight <- read.csv(file = here(
  "data/cross-cultural",
  "tightness.csv"
)) %>%
  rename(country = Country) %>%
  mutate(iso = countrycode(country,
    origin = "country.name",
    destination = "iso3c"
  )) %>%
  select(tightness = Tightness, iso, country)

# hofstede/residential mobility
DF_indcol <- read.csv(file = here(
  "data/cross-cultural",
  "hofstede_resmobility_simulated.csv"
)) %>%
  mutate(iso = countrycode(Matched,
    origin = "country.name",
    destination = "iso3c"
  )) %>%
  mutate(country = countrycode(iso,
    origin = "iso3c",
    destination = "country.name"
  )) %>%
  select(resmobility:country)


# religiosity
DF_relig <- read.csv(file = here(
  "data/cross-cultural",
  "worldreligiosity.csv"
)) %>%
  mutate(iso = countrycode(country,
    origin = "country.name",
    destination = "iso3c"
  )) %>%
  select(X2011:X2014, country, iso) %>%
  mutate(relig_mean = rowMeans(cbind(X2011, X2012, X2013, X2014), na.rm = TRUE)) %>%
  select(iso, country, relig_mean)
```

#Combine datasets
```{r}
# combine datasets
DF_combined <- bind_rows(
  DF_culture,
  DF_relation,
  DF_respon,
  DF_tight,
  DF_relig,
  DF_GDP,
  DF_indcol
) %>%
  group_by(iso) %>%
  summarise(
    across(everything(),
      ~ dplyr::first(na.omit(.x)),
      .names = "{.col}"
    ),
    .groups = "drop"
  )

# organize countries sampled in study
DF_combined$sample <- ifelse(DF_combined$iso %in% sampled, "yes", "no")

# save dataset
write.csv(DF_combined,
  file = here(
    "data/final-data",
    "crossculturalmod_simulated.csv"
  ), row.names = F
)
```
