---
title: "Figure 3: Cross-cultural Analyses"
author: "Nicholas A. Coles"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Load libraries
```{r lib}
library(tidyverse)
library(here)
library(BayesFactor)
library(metafor)
library(stringr)

options(scipen = 999)

i_am('code/Figure3.Rmd')
```

#Prep data for Fig 3a
```{r}
# open data
df <- 
  read.csv(file = here("data",
                       "unique_country_effect_sizes.csv")
           ) %>% 
  select(country:ss_var)

# list of effect size columns and variance columns
effect_size_columns <- c("pa_effect_size", "na_effect_size",
                         "optimistic_effect_size","ls_effect_size",
                         "envy_effect_size", "indebted_effect_size")

variance_columns <- c("pa_var", "na_var", "optimistic_var",
                         "ls_var", "envy_var", "indebted_var")

# use lapply to fit models for each pair of effect size and variance
m.ic <- lapply(1:length(effect_size_columns), function(i) {
  rma.mv(yi = df[[effect_size_columns[i]]],
         V = df[[variance_columns[i]]],
         random = list(~ 1 | intervention_condition, ~ 1 | country),
         data = df)})

# store the results with a name reflecting the effect size and variance pair
names(m.ic) <- paste(effect_size_columns)

# evaluate relative importance of variance components for each outcome
lapply(m.ic, function(model){
   model$sigma2[2] / model$sigma2[1]})
```

# Pnorm
```{r}
# compute probability > 0
effect_prob <- function(effect_name, reverse = FALSE) {
  mean_val <- m.ic[[effect_name]][["b"]]
  sd_val <- sqrt(m.ic[[effect_name]][["sigma2"]][[2]])
  prob <- pnorm(q = 0, mean = mean_val, sd = sd_val) * 100
  if (reverse) prob else 100 - prob
}

# create the table
distribution_results <- data.frame(
  outcome = c("PA", "NA", "Optimism", "Life Satisfaction", "Envy", "Indebtedness"),
  distribution = c(
    effect_prob("pa_effect_size"),
    effect_prob("na_effect_size", reverse = TRUE),
    effect_prob("optimistic_effect_size"),
    effect_prob("ls_effect_size"),
    effect_prob("envy_effect_size", reverse = TRUE),
    effect_prob("indebted_effect_size")
  ),
  opposite_distribution = c(
    effect_prob("pa_effect_size", reverse = TRUE),
    effect_prob("na_effect_size"),
    effect_prob("optimistic_effect_size", reverse = TRUE),
    effect_prob("ls_effect_size", reverse = TRUE),
    effect_prob("envy_effect_size"),
    effect_prob("indebted_effect_size", reverse = TRUE)
))

print(distribution_results)
```

```{r}

d.c <- lapply(effect_size_columns, function(effect_size) {
  
  d.c <- df %>%
    group_by(country) %>%
    summarise(m = mean(.data[[effect_size]]), .groups = "drop") %>%
    
    # add [jittered] y-value to assist with plotting
    mutate(y = 0,
           y = jitter(y, .1)) %>%
    
    # labels most extreme observations (in terms of min and max)
    mutate(label = if_else(m == min(m),
                           true = country,
                           false = ""),
           label = if_else(m == max(m),
                           true = country,
                           false = label)) %>%
    
    # include effect size name for reference
    mutate(effect_size = effect_size)
  
  return(d.c)
})

d.c <- bind_rows(d.c) 
d.c <- d.c %>% select(-y, -label)

mutate_country_results <- d.c %>%
  mutate(
    is_negative = case_when(
      effect_size == "na_effect_size" ~ m > 0,
      effect_size == "envy_effect_size" ~ m > 0,
      TRUE                            ~ m < 0
    )
  )

country_results <- mutate_country_results %>%
  group_by(effect_size) %>%
  summarise(
    opposite_countries_count = sum(is_negative, na.rm = TRUE),
    opposite_countries_prop = opposite_countries_count/34,
    countries = str_c(country[is_negative], collapse = "\n"),
    .groups = "drop"
  ) %>%
  rename(outcome = effect_size) %>%
  mutate(
    outcome = recode(
      outcome,
      "pa_effect_size"         = "PA",
      "na_effect_size"         = "NA",
      "optimistic_effect_size" = "Optimism",
      "ls_effect_size"         = "Life Satisfaction",
      "envy_effect_size"       = "Envy",
      "indebted_effect_size"   = "Indebtedness"
    )
  ) 

print(country_results)

```

# load and plot data
```{r}
universality_data <- left_join(distribution_results, country_results, by = "outcome")

viz.DF <- 
  universality_data %>%
  
  # clean factors
  mutate(outcome = factor(outcome,
                          levels = c("PA",
                                     "Optimism",
                                     "NA",
                                     "Indebtedness",
                                     "Life Satisfaction",
                                     "Envy"),
                          labels = c("Positive affect",
                                     "Optimism",
                                     "Negative affect",
                                     "Indebtedness",
                                     "Life satisfaction",
                                     "Envy")
                          ),
         countries = str_replace_all(countries,
                                     "\n",
                                     ", ")
         )
```

```{r}
fig3a <- 
  ggplot(data = viz.DF,
       aes(y = fct_rev(outcome),
           x = opposite_distribution,
           label = countries)) +
  geom_col(alpha = .5,
           fill = 'blue') +
  geom_text(aes(x = 18),
            size = 3,
            hjust = 0) +
  theme_classic() +
  xlim(0,100) +
  xlab('theory-inconsistent proportion of estimated distribution') +
  ylab('outcome')
```

# Prep data for figure 3b
```{r}
country.DF <-
  # open data
  read.csv(here('data',
                'unique_country_effect_sizes.csv'
                )
           ) %>% 
  
  # select relevant outcomes
  select(
    pa_effect_size,
    na_effect_size,
    optimistic_effect_size,
    ls_effect_size, 
    envy_effect_size, 
    indebted_effect_size,
    country) %>% 
  
  # summarise
  group_by(country) %>% 
  summarise(across(everything(), mean, na.rm = TRUE))

mod.DF <-
  read.csv(here('data',
                'GlobalGratitude_CrossCulturalMod.csv'
                )
           ) %>% 
  filter(sample == "sampled") %>% 
  mutate(country = country_name) %>% 
  select(-c(country_code,
            country_name))

```

# Open cross-cultural moderator data
```{r}
# join
DF <-
  left_join(x = country.DF,
            y = mod.DF,
            by = "country")

# delete vestigial
rm(country.DF,
   mod.DF)
```

# Bayesian correlation analyses
```{r}
# created expanded list of outcome-moderator combinations
out.list <- 
  c('pa_effect_size',
    'na_effect_size',
    'optimistic_effect_size',
    'ls_effect_size',
    'envy_effect_size',
    'indebted_effect_size')

mod.list <-
  c("relational_mobility",
    "responsibilism",
    "tightness",
    "relig_mean",
    "mean_GDP",
    "resmobility",
    "power.distance",
    "individualism",
    "motivation",
    "uncertainty.avoidance",
    "long.term.orientation",
    "indulgence")

expanded.list <- 
  expand_grid(out.list,
              mod.list)

results <- sapply(X = seq_len(nrow(expanded.list)), # iterate through each row of list
                  simplify = F,
                  FUN = function(i){
                    df <- DF %>% 
                      select(expanded.list$out.list[i],
                             expanded.list$mod.list[i])
                    
                    names(df) <- c('x', 'y')
                      
                    
                    cor.est <- 
                      cor(x = df$x,
                          y = df$y,
                          use = "pairwise.complete.obs",
                          method = 'pearson')
                    
                    bf.est <- 
                      correlationBF(x = df$x,
                                    y = df$y)
                    
                    cbind(outcome = expanded.list$out.list[i],
                          moderator = expanded.list$mod.list[i],
                          cor = cor.est,
                          bf = extractBF(bf.est)$b) %>% 
                      return()
       })

# combine list
results <- 
  do.call(rbind, results) %>% 
  as.data.frame() %>% 
  mutate(cor = as.numeric(cor),
         cor = round(cor, 2),
         bf = as.numeric(bf),
         logbf = log(bf),
         logbf = round(logbf, 2)) %>% 
  
  # clean aesthetics
  mutate(outcome = factor(outcome,
                          levels = c("pa_effect_size",
                                     "na_effect_size",
                                     "optimistic_effect_size",
                                     "ls_effect_size",
                                     "envy_effect_size",
                                     "indebted_effect_size"),
                          labels = c("Positive affect",
                                     "Negative affect",
                                     "Optimism",
                                     "Life satisfaction",
                                     "Envy",
                                     "Indebtedness")
                          )
         ) %>% 
  mutate(moderator = factor(moderator,
                            levels = c("individualism",
                                       "tightness",
                                       "relational_mobility",
                                       "resmobility",
                                       "responsibilism",
                                       "relig_mean",
                                       "mean_GDP",
                                       "power.distance",
                                       "motivation",
                                       "uncertainty.avoidance",
                                       "long.term.orientation",
                                       "indulgence"),
                            
                            labels = c("Individualism",
                                       "Tightness",
                                       "Relational mobility",
                                       "Residential mobility",
                                       "Responsibilism",
                                       "Religiosity",
                                       "GDP",
                                       "Power distance",
                                       "Motivation",
                                       "Uncertainty avoidance",
                                       "Long term orientation",
                                       "Indulgence"
                                       )
                            )
         )

# Make minor edit to label
results <- results %>% 
    mutate(cor.lab = paste0("paste(", 
                            "italic(r), ' = ",
                            cor,
                            "')"
                            )
           )

# restructure
results <- results %>% 
  mutate(outcome = fct_reorder(outcome, -logbf),
         moderator = fct_reorder(moderator, -logbf))

# recalculate bf scale
results <- results %>% 
  mutate(bf.type = 
           if_else(bf >.9999,
                   "BF['1,0']",
                   "BF['0,1']"),
         bf.tran =
           if_else(bf >.9999,
                   bf,
                   1 / bf),
         bf.tran = 
           round(bf.tran, 
                 2),
         bf.tran.dir = 
           if_else(bf > .9999,
                   bf.tran,
                   bf.tran * (-1)),
         bf.lab = 
           paste0("paste(",
                  "italic(", 
                  bf.type,
                  ")",
                  ", ' = ",
                  bf.tran,
                  "')")
         )
```

# For paper
```{r}
cor.test(DF$optimistic_effect_size, 
         DF$indulgence)

cor.test(DF$ls_effect_size, 
         DF$power.distance)

cor.test(DF$indebted_effect_size, 
         DF$mean_GDP)
```


# Final figure 3b
```{r}
fig3b <-
  ggplot(data = results,
       aes(x = moderator,
           y = fct_rev(outcome),
           fill = bf.tran.dir,
           label = bf.lab)) +
  geom_tile(aes(color = cor),
            size = 1,
            width = .97, height = 0.97) +
  
  scale_color_gradient2(
    low = "red", mid = "white", high = "blue",
    midpoint = 0, limits = c(-1, 1),
    name = expression("Pearson's " * italic('r'))
    ) +
  
  scale_fill_gradient2(
    high = "#1b7837",
    mid = "white",
    low = "black", 
    midpoint = 1,
    limits = c(-8, 8),
    name = "Bayes factor",
    labels = c("-4" = expression(BF['0,1'] == 4),
               "-2" = expression(BF['0,1'] == 2),
               "0" = expression(BF['1,0'] == 1),
               "2" = expression(BF['1,0'] == 2),
               "4" = expression(BF['1,0'] == 4)
               )
    ) +
  
  geom_text(aes(label = bf.lab),
                  parse = T,
                  nudge_y = .25,
                  size = 3.5) +
  
  geom_label(aes(label = cor.lab,
                 color = cor),
             parse = T,
             nudge_y = -.25,
             size = 3.5) +
  theme_classic() +
  labs(y = 
         expression("Country-level effects of gratitude interventions (" * italic('d') * ")"),
       x = "Country-level differences",
       fill = expression("Pearson's " * italic('r'))
       ) +
  theme(axis.line = element_blank(),
        axis.ticks = element_blank(),
        plot.background = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1),
        legend.title = element_text(size = 10, margin = margin(b = 15)),  
        legend.key.size = unit(.6, 'cm'))
```

#combine
```{r}
library(cowplot)

plot_grid(fig3a, 
          ggdraw(),
          fig3b, 
          labels = c("a", "", "b"), 
          nrow = 3,
          rel_heights = c(.2, .05, .75),
          rel_widths = c(.1, 1))
```
