---
title: "Figure 1: Cross-cultural viz"
author: "Nicholas A. Coles"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Load libraries
```{r lib}
library(tidyverse)
library(here)
library(countrycode)
library(cowplot)

options(scipen = 999)

i_am('code/Figure1.Rmd')
```

# Open country-specific effect sizes and moderator values
```{r}
country.DF <-
  # open data
  read.csv(here('data',
                'unique_country_effect_sizes.csv'
                )
           ) %>% 
  
  # select relevant outcomes
  select(
    pa_effect_size,
    na_effect_size,
    optimistic_effect_size,
    ls_effect_size, 
    envy_effect_size, 
    indebted_effect_size,
    country) %>% 
  
  # summarise
  group_by(country) %>% 
  summarise(across(everything(), mean, na.rm = TRUE))

mod.DF <-
  read.csv(here('data',
                'GlobalGratitude_CrossCulturalMod.csv'
                )
           ) %>% 
  mutate(country = country_name) %>% 
  select(-c(country_code,
            country_name))

rm(mod.list, out.list)
```

# Join
```{r}
# join
DF <-
  left_join(x = country.DF,
            y = mod.DF,
            by = "country") %>% 
  
  mutate(iso =
    countrycode(country,
                origin = "country.name",
                destination = "iso3c")
    )

# delete vestigial
# rm(country.DF,
#    mod.DF)
```

# Open cultural distance data
```{r}
# cultural distance
DF.cd <- read.csv(here('data',
                       "culturaldistance_table_combined.csv")) %>% 
  select(Name, United.States1981.2014) %>% 
  rename(country = Name,
         dist.us = United.States1981.2014) %>% 
  mutate(country = str_remove_all(country, "[:digit:]"),
         country = str_remove_all(country, "-"))
```

# Merge
```{r}
DF2 <- left_join(DF.cd,
                 DF,
                 by = 'country')
```

# Standardization of variables
```{r}
library(scales)
DF2 <-
  DF2 %>% 
  mutate_at(.vars = vars(dist.us,
                         rel_mob_mean : indulgence),
            ~ rescale(x = .,
                      to = c(-1, 1)))
```


# New attempt at top of Figure 1
```{r}
fig1.DF.new <-
  mod.DF %>% 
  pivot_longer(rel_mob_mean : indulgence) %>% 
  filter(name != 'rel_mob_mean',
         name != 'respon_mean') %>% 
  mutate(
    name = 
      fct_recode(name,
                 "Relational mobility" = "relational_mobility", 
                 "Responsibilism" = "responsibilism", 
                 "Tightness" = "tightness", 
                 "Religiosity" = "relig_mean",
                 "GDP" = "mean_GDP",
                 "Residential mobility" = "resmobility",
                 "Power distance" = "power.distance",
                 "Individualism" = "individualism",
                 "Motivation" = "motivation",
                 "Uncertainty avoidance" = "uncertainty.avoidance",
                 "Long term orientation" = "long.term.orientation",
                 "Indulgence" = "indulgence")
  )
```

```{r}
fig.1a <-
  ggplot(data = fig1.DF.new,
       aes(x = value)) +
  
  # facet wrap
  facet_wrap(~ name,
             scales = 'free',
             strip.position = 'bottom') +
  
  # plot all countries
  geom_density(alpha = .5,
               color = 'grey70') +
  
  # plot sampled countries
  geom_density(data = fig1.DF.new %>% 
               filter(sample == 'sampled'),
             alpha = .5,
             color = '#3C5488') +
  theme_classic() +
  theme(
    legend.position = 'none',
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.line.y = element_blank(),
    strip.placement = "outside",
    strip.background = element_blank()
  )
```


# Prep figure
```{r}
fig1.DF <- 
  DF %>% 
  select(country,
         rel_mob_mean : tightness, 
         relig_mean : indulgence) %>% 
  pivot_longer(cols = rel_mob_mean : indulgence) %>% 
  mutate(
    name = 
      fct_recode(name,
                 "Relational mobility" = "rel_mob_mean", 
                 "Responsibilism" = "respon_mean", 
                 "Tightness" = "tightness", 
                 "Religiosity" = "relig_mean",
                 "GDP" = "mean_GDP",
                 "Residential mobility" = "resmobility",
                 "Power distance" = "power.distance",
                 "Individualism" = "individualism",
                 "Motivation" = "motivation",
                 "Uncertainty Avoidance" = "uncertainty.avoidance",
                 "Long term orientation" = "long.term.orientation",
                 "Indulgence" = "indulgence")
  )
```

# Top facet (cross-cultural moderators)
```{r eval = F}
fig.1a <-
  ggplot(data = fig1.DF,
       aes(x = country,
           y = value,
           fill = country)) +
  facet_wrap(~ name,
             scales = 'free') +
  theme(axis.text.x = element_text(angle = 90, 
                                   hjust = 1)) +
  geom_bar(stat = 'identity') +
  theme_classic() +
  theme(legend.position = 'none',
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())
```

# Bottom facet (cultural distance)
Prep data
```{r}
DF2 <- DF2 %>% 
  mutate(
    sampled =
      if_else(is.na(pa_effect_size),
              'no', 
              'yes'),
    
    country = 
      countrycode(country,
                  origin = "country.name",
                  destination = "iso3c"),
    
    dist.us =
      replace_na(dist.us, 
                 0)
    )
```

plot
```{r}
fig.1b <-
  ggplot(
  data = DF2,
  aes(x = dist.us,
      y = .2)) +
  
  # add rug graph
  geom_linerange(
    data = DF2 %>% 
      filter(sampled == "no"),
    aes(ymin = 0, ymax = 0.1),
    color = 'grey50') +
  
  geom_linerange(
    data = DF2 %>% 
      filter(sampled == "yes"),
    aes(ymin = 0, ymax = 0.2,
        color = country)) +
  
  # add country labels
  geom_text(
    data = DF2 %>% 
      filter(sampled == "yes"),
    aes(label = country,
        color = country,
        y = .8),
    position = position_jitter(height = 0.5)) +
  
  # fix theme
  theme_classic() +
  theme(
    legend.position = 'none',
    axis.title.y = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.line.y = element_blank(),
    strip.background = element_blank()
  ) +
  xlab('Cultural distance (from USA)')
```

# Combine
```{r}
plot_grid(fig.1b,
          fig.1a,
          nrow = 2,
          labels = c('a', 'b'))
```

# Try to create map
```{r}
# open packages
library("sf")
library("rnaturalearth")
library("rnaturalearthdata")
library("ggspatial")

# download world data
world <- ne_countries(scale = "medium", 
                      returnclass = "sf")

# fix missing ISO values in world data
world[world$name == "France", ]$iso_a3 = "FRA"
world[world$name == "Norway", ]$iso_a3 = "NOR"
```

# Globe?
```{r}
world <- ne_countries(scale = "medium", 
                      returnclass = "sf")

fig.1c <- ggplot() +
  # plot map layer
  layer_spatial(data = world,
                color = NA) +
  layer_spatial(data = 
                  world %>% 
                  filter(iso_a3 %in% DF$iso),
                aes(fill = iso_a3)) +
  
  # change coordinate projections
  coord_sf(crs = 'ESRI:54030') +
  cowplot::theme_minimal_grid() +
  theme(legend.position = 'none')
```

# Combine
```{r}
ac <- 
  plot_grid(fig.1c,
            fig.1a,
          ncol = 2,
          labels = c('b', 'c'))

plot_grid(fig.1b, 
          ac, 
          nrow = 2,
          labels = c('a', ''))
```


