---
title: "Figure 1: Cross-cultural viz"
author: "Nicholas A. Coles"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Load libraries
```{r lib}
library(tidyverse)
library(here)
library(metafor)
library(stringr)

i_am('code/Figure4.Rmd')
```

Prep data
```{r}
# open data

df <- 
  read.csv(file = here("data",
                       "unique_country_effect_sizes.csv")
           ) %>% 
  select(country:ss_var)

# List of effect size columns and variance columns
effect_size_columns <- c("pa_effect_size", "na_effect_size",
                         "optimistic_effect_size","ls_effect_size",
                         "envy_effect_size", "indebted_effect_size")

variance_columns <- c("pa_var", "na_var", "optimistic_var",
                         "ls_var", "envy_var", "indebted_var")

# Use lapply to fit models for each pair of effect size and variance
m.ic <- lapply(1:length(effect_size_columns), function(i) {
  rma.mv(yi = df[[effect_size_columns[i]]],
         V = df[[variance_columns[i]]],
         random = list(~ 1 | intervention_condition, ~ 1 | country),
         data = df)})

# Store the results with a name reflecting the effect size and variance pair
names(m.ic) <- paste(effect_size_columns)

# evaluate relative importance of variance components for each outcome
lapply(m.ic, function(model){
   model$sigma2[2] / model$sigma2[1]})
```

# Pnorm
```{r}
# Compute probability > 0
effect_prob <- function(effect_name, reverse = FALSE) {
  mean_val <- m.ic[[effect_name]][["b"]]
  sd_val <- sqrt(m.ic[[effect_name]][["sigma2"]][[2]])
  prob <- pnorm(q = 0, mean = mean_val, sd = sd_val) * 100
  if (reverse) prob else 100 - prob
}

# Create the table
distribution_results <- data.frame(
  outcome = c("PA", "NA", "Optimism", "Life Satisfaction", "Envy", "Indebtedness"),
  distribution = c(
    effect_prob("pa_effect_size"),
    effect_prob("na_effect_size", reverse = TRUE),
    effect_prob("optimistic_effect_size"),
    effect_prob("ls_effect_size"),
    effect_prob("envy_effect_size", reverse = TRUE),
    effect_prob("indebted_effect_size")
  ),
  opposite_distribution = c(
    effect_prob("pa_effect_size", reverse = TRUE),
    effect_prob("na_effect_size"),
    effect_prob("optimistic_effect_size", reverse = TRUE),
    effect_prob("ls_effect_size", reverse = TRUE),
    effect_prob("envy_effect_size"),
    effect_prob("indebted_effect_size", reverse = TRUE)
))

print(distribution_results)
```

```{r}

d.c <- lapply(effect_size_columns, function(effect_size) {
  
  d.c <- df %>%
    group_by(country) %>%
    summarise(m = mean(.data[[effect_size]]), .groups = "drop") %>%
    
    # add [jittered] y-value to assist with plotting
    mutate(y = 0,
           y = jitter(y, .1)) %>%
    
    # labels most extreme observations (in terms of min and max)
    mutate(label = if_else(m == min(m),
                           true = country,
                           false = ""),
           label = if_else(m == max(m),
                           true = country,
                           false = label)) %>%
    
    # include effect size name for reference
    mutate(effect_size = effect_size)
  
  return(d.c)
})

d.c <- bind_rows(d.c) 
d.c <- d.c %>% select(-y, -label)

mutate_country_results <- d.c %>%
  mutate(
    is_negative = case_when(
      effect_size == "na_effect_size" ~ m > 0,
      effect_size == "envy_effect_size" ~ m > 0,
      TRUE                            ~ m < 0
    )
  )

country_results <- mutate_country_results %>%
  group_by(effect_size) %>%
  summarise(
    opposite_countries_count = sum(is_negative, na.rm = TRUE),
    opposite_countries_prop = opposite_countries_count/34,
    countries = str_c(country[is_negative], collapse = "\n"),
    .groups = "drop"
  ) %>%
  rename(outcome = effect_size) %>%
  mutate(
    outcome = recode(
      outcome,
      "pa_effect_size"         = "PA",
      "na_effect_size"         = "NA",
      "optimistic_effect_size" = "Optimism",
      "ls_effect_size"         = "Life Satisfaction",
      "envy_effect_size"       = "Envy",
      "indebted_effect_size"   = "Indebtedness"
    )
  ) 

print(country_results)

```
```{r}
#combine

final_results <- left_join(distribution_results, country_results, by = "outcome")

write.csv(final_results, 
          file = here('data',
                      "universality_data.csv"))
```

