---
title: "GlobalGratitude_MixedModels"
author: "Nicholas A. Coles, Annabel V. Dang"
description: "Calculate pairwise comparisons for Supplemental Table 3"
output: html_document
editor_options: 
  chunk_output_type: console
---
# Load packages
```{r}
# install packages
source("setup.R")

# allow for Type III Sums of Square
options(contrasts = c("contr.sum", "contr.poly"))
```

# Open data
```{r}
# fetch survey
DF <- readRDS(
  file = here("data/final-data", "globalgratitude_final_cleaned.Rds")
)

# select relevant variables
DF <-
  DF %>%
  select(
    Status:envy_8,
    lab:condition_type,
    me_attention,
    meals_attention
  ) %>%
  # fix variable formatting
  mutate_at(
    c(
      "ResponseId",
      "lab",
      "condition",
      "condition_type"
    ),
    as.factor
  )
```

# Examine reliability
```{r}
# Gratitude
gra <- psych::alpha(
  DF %>% select(grateful, appreciative, thankful)
)$total$raw_alpha

# Positive affect
pas <- psych::alpha(
  DF %>% select(happy, satisfied, content, joyful, pleased)
)$total$raw_alpha

# Optimism
opt <- psych::alpha(DF %>% select(optimistic, hopeful))$total$raw_alpha

# Negative affect
neg <- psych::alpha(
  DF %>% select(sad, depressed, anxious, nervous)
)$total$raw_alpha

# Indebtedness
ind <- psych::alpha(DF %>% select(indebted, obligated))$total$raw_alpha

# Envy
env <- psych::alpha(DF %>% select(envious, bitter, jealous))$total$raw_alpha

# Life satisfaction
lif <- psych::alpha(DF %>% select(ls_1, ls_2, ls_3, ls_4, ls_5))$total$raw_alpha

# Sense of self
sen <- psych::alpha(
  DF %>% select(self_image_circle, self_image)
)$total$raw_alpha

# Combine into a tidy table
overall_alpha <- data.frame(
  outcome = c(
    "Gratitude",
    "Positive Affect",
    "Optimism",
    "Negative Affect",
    "Indebtedness",
    "Envy",
    "Life Satisfaction",
    "Sense of Self"
  ),
  alpha = c(gra, pas, opt, neg, ind, env, lif, sen)
)

write.csv(
  overall_alpha,
  file = here(
    "data/output",
    "reliability_scores.csv"
  )
)
```

# Calculate scales
```{r}
DF <- DF %>%
  rowwise() %>%
  mutate(
    # gratitude
    gratitude_mean = mean(c(grateful, appreciative, thankful), na.rm = T),

    # positive affect
    pa_mean = mean(c(happy, satisfied, content, joyful, pleased), na.rm = T),

    # optimism
    optimistic_mean = mean(c(optimistic, hopeful), na.rm = T),

    # negative affect
    na_mean = mean(c(sad, depressed, anxious, nervous), na.rm = T),

    # indebtendess
    indebted_mean = mean(c(indebted, obligated), na.rm = T),

    # envy
    envy_mean = mean(c(envious, bitter, jealous), na.rm = T),

    # life satisfaction
    ls_mean = mean(c(ls_1, ls_2, ls_3, ls_4, ls_5), na.rm = T),

    # sense of self
    ss_mean = mean(c(self_image_circle, self_image), na.rm = T)
  ) %>%
  ungroup()

# delete vestigial variables
DF <- DF %>%
  select(
    -c(
      grateful,
      appreciative,
      thankful,
      happy,
      satisfied,
      content,
      joyful,
      pleased,
      optimistic,
      hopeful,
      depressed,
      sad,
      anxious,
      nervous,
      indebted,
      obligated,
      envious,
      bitter,
      jealous,
      ls_1,
      ls_2,
      ls_3,
      ls_4,
      ls_5,
      self_image_circle,
      self_image
    )
  )

# create list of outcome variables
out.list <- c(
  "gratitude_mean",
  "pa_mean",
  "optimistic_mean",
  "na_mean",
  "indebted_mean",
  "guilty",
  "envy_mean",
  "ls_mean",
  "ss_mean",
  "ladder"
)
```

# Analyses
## Pre-registered analyses (full)
```{r}
# for each outcome build model
pr.results <- sapply(
  X = out.list,
  simplify = F,
  FUN = function(x) {
    m <- lmer(
      as.formula(paste0(
        x,
        "~ condition + (1 + condition | lab)"
      )),
      data = DF
    )

    emm <- emmeans(
      m,
      pairwise ~ condition,
      adjust = "none",
      pbkrtest.limit = 99999
    )

    return(list(
      m = summary(m),
      emm = emm
    ))
  }
)
```

### Bind rows and export
```{r}
contrast.table <-
  rbind(
    cbind(
      outcome = "gratitude",
      pr.results$gratitude_mean$emm$contrasts %>%
        as.data.frame()
    ),
    cbind(
      outcome = "pa",
      pr.results$pa_mean$emm$contrasts %>%
        as.data.frame()
    ),
    cbind(
      outcome = "optimism",
      pr.results$optimistic_mean$emm$contrasts %>%
        as.data.frame()
    ),
    cbind(
      outcome = "na",
      pr.results$na_mean$emm$contrasts %>%
        as.data.frame()
    ),
    cbind(
      outcome = "indebted",
      pr.results$indebted_mean$emm$contrasts %>%
        as.data.frame()
    ),
    cbind(
      outcome = "guilty",
      pr.results$guilty$emm$contrasts %>%
        as.data.frame()
    ),
    cbind(
      outcome = "envy",
      pr.results$envy_mean$emm$contrasts %>%
        as.data.frame()
    ),
    cbind(
      outcome = "ls",
      pr.results$ls_mean$emm$contrasts %>%
        as.data.frame()
    ),
    cbind(
      outcome = "ss",
      pr.results$ss_mean$emm$contrasts %>%
        as.data.frame()
    ),
    cbind(
      outcome = "ladder",
      pr.results$ladder$emm$contrasts %>%
        as.data.frame()
    )
  )

contrast.table <- contrast.table %>%
  mutate(
    p.value = stars.pval(p.value),
    estimate = round(estimate, 2),
    SE = round(SE, 2),
    df = round(df, 2),
    t.ratio = round(t.ratio, 2)
  )

write.csv(
  contrast.table,
  file = here(
    "data/output",
    "si_table_3.csv"
  )
)
```

## Pre-registered analyses (full)
```{r}
# for each outcome build model
pr.results <- sapply(
  X = out.list,
  simplify = F,
  FUN = function(x) {
    m <- lmer(
      as.formula(paste0(
        x,
        "~ condition + (1 + condition | lab)"
      )),
      data = DF
    )

    emm <- emmeans(
      m,
      pairwise ~ condition,
      adjust = "none",
      pbkrtest.limit = 99999
    )

    return(list(
      m = summary(m),
      emm = emm
    ))
  }
)
```

### Bind rows and export
```{r}
contrast.table <-
  rbind(
    cbind(
      outcome = "gratitude",
      pr.results$gratitude_mean$emm$contrasts %>%
        as.data.frame()
    ),
    cbind(
      outcome = "pa",
      pr.results$pa_mean$emm$contrasts %>%
        as.data.frame()
    ),
    cbind(
      outcome = "optimism",
      pr.results$optimistic_mean$emm$contrasts %>%
        as.data.frame()
    ),
    cbind(
      outcome = "na",
      pr.results$na_mean$emm$contrasts %>%
        as.data.frame()
    ),
    cbind(
      outcome = "indebted",
      pr.results$indebted_mean$emm$contrasts %>%
        as.data.frame()
    ),
    cbind(
      outcome = "guilty",
      pr.results$guilty$emm$contrasts %>%
        as.data.frame()
    ),
    cbind(
      outcome = "envy",
      pr.results$envy_mean$emm$contrasts %>%
        as.data.frame()
    ),
    cbind(
      outcome = "ls",
      pr.results$ls_mean$emm$contrasts %>%
        as.data.frame()
    ),
    cbind(
      outcome = "ss",
      pr.results$ss_mean$emm$contrasts %>%
        as.data.frame()
    ),
    cbind(
      outcome = "ladder",
      pr.results$ladder$emm$contrasts %>%
        as.data.frame()
    )
  )

contrast.table <- contrast.table %>%
  mutate(
    p.value = stars.pval(p.value),
    estimate = round(estimate, 2),
    SE = round(SE, 2),
    df = round(df, 2),
    t.ratio = round(t.ratio, 2)
  )

write.csv(
  contrast.table,
  file = here(
    "data/output",
    "si_table_3.csv"
  )
)
```

## Pre-registered analysis (reduced)
```{r}
pr.results.red <- sapply(
  X = out.list,
  simplify = F,
  FUN = function(x) {
    m <- lmer(
      as.formula(paste0(
        x,
        "~ condition_type + (1 + condition_type | lab)"
      )),
      data = DF
    )

    emm <- emmeans(
      m,
      pairwise ~ condition_type,
      adjust = "none",
      pbkrtest.limit = 99999
    )

    return(list(
      m = summary(m),
      emm = emm
    ))
  }
)

saveRDS(
  pr.results.red,
  file = here(
    "data/output",
    "si_regression_output.Rds"
  )
)
```