---
title: "Paper_Statistics"
author: "Nicholas A. Coles, Annabel V. Dang"
description: "Organize statistics in manuscript"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Load packages
```{r}
# install packages
source("setup.R")
```

# Abstract
```{r}
# Participant n
DF <- readRDS(file = here("data/final-data", "globalgratitude_final_cleaned.Rds"))

nrow(DF)

# Overall effect sizes for each outcome
ef <- read.csv(file = here("quality-checks/sensitivity-analyses", "si_table_4.csv")) %>%
  filter(Sample == "Full") %>%
  select(Outcome, Cohen.s.d)

print(ef)

# Overall tau
tau <- read.csv(file = here("quality-checks/sensitivity-analyses", "si_table_4.csv")) %>%
  filter(Sample == "Full") %>%
  select(Outcome, τc, τp)

print(tau)
```

#Methodology
Participant N
```{r}
# Calculate original participant n
DF_org <-
  readRDS(file = here("data/raw-data", "globalgratitude_final.Rds"))

DF_USA_02b <-
  read.csv(file = here(
    "data/raw-data",
    "USA_02b_raw_harmonized.csv"
  )) %>% select(Status:pageNo)

DF_USA_02c <-
  read.csv(file = here(
    "data/raw-data",
    "USA_02c.csv"
  )) %>% select(Status:pageNo)

# Match columns
DF_org <- DF_org %>%
  mutate(across(names(DF_USA_02c), ~ {
    # matching character columns
    if (is.character(DF_USA_02c[[cur_column()]])) {
      return(as.character(.))
    }

    # matching numeric or integer columns
    else if (is.numeric(DF_USA_02c[[cur_column()]])) {
      return(as.numeric(.))
    } else {
      return(.)
    }
  }))

combined_DF <- bind_rows(DF_org, DF_USA_02b, DF_USA_02c)

# Remove test and invalid responses
combined_DF <-
  combined_DF %>%
  # removed test links
  filter(
    DistributionChannel != "preview",
    # 4/22/2024 TUR_01 used real link for testing purposes
    ResponseId != "R_42KUGZSS76NgWH7",
    ResponseId != "R_4W4EXfgeyk1rCYF",
    ResponseId != "R_45Z862EIfzYcin4",
    ResponseId != "R_7BhJx9Ci7THupmF",
    ResponseId != "R_42Lv9fg5qi9V9xm",
    ResponseId != "R_2kFa26mh78uevnz",
    ResponseId != "R_4DRThnH8LgbEvM8",
    ResponseId != "R_4r1kAEqQCo1PNn6",
    ResponseId != "R_4GQErqyYDlRWVwZ",
    ResponseId != "R_4SGF0GCHSHIN0ls",
    ResponseId != "R_6Pndj5c7sr1pcU3",
    ResponseId != "R_8lQxsY2ITg7HKh1",
    ResponseId != "R_8HXsI5PQftiJUYk",
    ResponseId != "R_8iVWI3CN49ACiUp",
    # 6/6/2024 Removed USA_01 duplicate data
    ResponseId != "R_6rDfD5u84z6WufT",
    # 11/21/2024 Removed DZA_01 test data
    ResponseId != "R_4ioYJK1zR2FgR4R",
    ResponseId != "R_4OvlyOmeTsmLpFn",
    ResponseId != "R_4BA1gbglSYnVyDK",

    # remove invalid data
    consent %in% c(0, 1)
  )

nrow(combined_DF)

# Number of participants who did not provide consent

consent <- combined_DF %>% filter(consent == 0)

nrow(consent)

# Number of participants that did not finish at least 95% of the survey

finish <- combined_DF %>% filter(Progress > 0, Progress < 95)

nrow(finish)

# Number of participants without site data

site <- combined_DF %>% filter(Progress >= 95, lab == "")

nrow(site)
```

Demographics
```{r}
# Calculate sex percentage
DF <- readRDS(file = here("data/final-data", "globalgratitude_final_cleaned.Rds"))

sex_factor <- factor(DF$sex,
  levels = c(1, 2, 3, 4),
  labels = c("Male", "Female", "Other/Not-Reported", "Other/Not-Reported")
)

# Replace NA values with "Other/Not-Reported"
sex_factor <- forcats::fct_explicit_na(sex_factor, na_level = "Other/Not-Reported")

# Frequency table
sex_table <- as.data.frame(table(sex_factor))
names(sex_table) <- c("Sex", "Count")

# Add percentages
sex_table$Percentage <- round(100 * sex_table$Count / sum(sex_table$Count), 1)

sex_table

# Calculate Age
DF <- readRDS(file = here("data/final-data", "globalgratitude_final_cleaned.Rds")) %>%
  filter(
    !is.na(age),
    # Remove outliers
    age >= 10 & age <= 100
  )

mean(DF$age)
SD(DF$age)
```

#Procedure
Reliability Scores
```{r}
# Reliability scores
reliability <-
  read.csv(file = here(
    "data/output",
    "reliability_scores.csv"
  ))

print(reliability)
```

#Results
Overall Effect Sizes
```{r}
# Overall effect sizes, CI, p-values
overall_ef <-
  read.csv(file = here(
    "data/output",
    "pooled_effect_size.csv"
  ))

print(overall_ef)
```

Heterogeneity
```{r}
# Overall heterogeneity
heterogeneity <- read.csv(file = here("data/output", "overall_heterogeneity.csv"))

print(heterogeneity)

# Overall tau
tau <- read.csv(file = here("quality-checks/sensitivity-analyses", "si_table_4.csv")) %>%
  filter(Sample == "Full") %>%
  select(Outcome, τc, τp)

print(tau)
```

Prediction Intervals
```{r}
# Prediction intervals
prediction <- heterogeneity <- read.csv(file = here("data/output", "prediction_intervals.csv")) %>% select(effect_size, practice_pi_lb, practice_pi_ub, country_pi_lb, country_pi_ub)

print(prediction)
```

Cross-Cultural Consistency
```{r}
# Cross-Cultural consistency
consistency <- heterogeneity <- read.csv(file = here("data/output", "cultural_consistency.csv")) %>% select(-opposite_countries_prop, -countries)

print(consistency)
```

Cross-Cultural Moderators
```{r}
# Cross-cultural moderators
moderators <- read.csv(file = here("data/output", "moderators.csv"))

specific_rows <- moderators[c(36, 43, 64, 65), ]
tightness_rows <- moderators %>%
  filter(moderator == "Tightness") %>%
  slice(1:4)

moderators_selected <- bind_rows(specific_rows, tightness_rows) %>%
  select(outcome:ci.upper)

print(moderators_selected)
```

#Supplemental Information
```{r}
# Pre-registered analysis (reduced)
analysis <- readRDS(file = here("data/output", "si_regression_output.Rds"))

# Loop and print summary
for (outcome in names(analysis)) {
  cat("\n---", outcome, "---\n")
  print(analysis[[outcome]])
} 
```

