---
title: "GlobalGratitude_QualityChecks"
author: "Nicholas A. Coles, Annabel V. Dang"
description: "Create summary table of each site's quality checks"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Load packages
```{r lib}
# load packages
source("setup.R")
```

#Setup data file
```{r}
# load the workbook
df <- loadWorkbook(file = here("quality-checks/lab-quality-checks", "qualitychecks.xlsx"))

# get sheet names
sheet_names <- names(df)

# remove the first sheet
removeWorksheet(df, sheet = sheet_names[1])

# save to a temp file
temp_file <- tempfile(fileext = "temp_qualitychecks.xlsx")
saveWorkbook(df, temp_file, overwrite = TRUE)

# re-read sheet names
new_sheets <- getSheetNames(temp_file)
```

#Standardize datasets
```{r}
# standardize sheet with mismatched columns
USA_02b <- readWorkbook(temp_file, sheet = new_sheets[37])

# standardize sheet with missing column
USA_02c <- readWorkbook(temp_file, sheet = new_sheets[38])
USA_02c$me_attention <- as.character(NA)

# combine sheets 1-36 and 39 into a dataframe
selected_indices <- c(1:36, 39)

selected_sheets <- lapply(selected_indices, function(i) {
  readWorkbook(temp_file, sheet = new_sheets[i])
})

combined_df <- bind_rows(selected_sheets) %>%
  # column response was accidentally deleted when conducting quality checks
  mutate(lab = ifelse(ResponseId == "R_8EFEKmOIkETMemi", "ITA_01", lab)) %>%
  filter(!is.na(lab))

# loop over columns in USA_02b and USA_02c to match the types from combined_df
match_column_types <- function(df, reference_df) {
  for (col in names(df)) {
    # check if the column exists in combined_df
    if (col %in% names(reference_df)) {
      # match the column type from combined_df
      target_type <- class(reference_df[[col]])

      # convert the column type in df to match the target type
      if (target_type == "numeric") {
        df[[col]] <- as.numeric(df[[col]])
      } else if (target_type == "character") {
        df[[col]] <- as.character(df[[col]])
      } else if (target_type == "factor") {
        df[[col]] <- as.factor(df[[col]])
      } else if (target_type == "logical") {
        df[[col]] <- as.logical(df[[col]])
      }
    }
  }
  return(df)
}

# apply to USA_02b and USA_02c
USA_02b <- match_column_types(USA_02b, combined_df)
USA_02c <- match_column_types(USA_02c, combined_df)

# final sheets
final_df <- bind_rows(combined_df, USA_02b, USA_02c) %>%
  # fix issues with extra spaces
  mutate(Category = str_replace(Category, "^no\\s+$", "no")) %>%
  mutate(Category = if_else(Category == "No", "no", Category))
```

#Final Statistics
```{r}
country_summary <- final_df %>%
  group_by(lab, Category) %>%
  summarise(count = n(), .groups = "drop") %>%
  group_by(lab) %>%
  mutate(percentage = round(count / sum(count) * 100, 1)) %>%
  ungroup()

condition_summary <- final_df %>%
  group_by(condition, Category) %>%
  summarise(count = n(), .groups = "drop") %>%
  group_by(condition) %>%
  mutate(percentage = round(count / sum(count) * 100, 1)) %>%
  ungroup()
```

#Create xlsx sheet
```{r}
# Create a workbook
wb <- createWorkbook()

# add sheets
addWorksheet(wb, "Country_Summary")
addWorksheet(wb, "Condition_Summary")

# write data to sheets
writeData(wb, "Country_Summary", country_summary)
writeData(wb, "Condition_Summary", condition_summary)

# save the workbook
saveWorkbook(wb, here("quality-checks/lab-quality-checks", "qualitychecks_summary.xlsx"), overwrite = TRUE)
```

#Conduct quality checks
```{r}
# select response_id and category
final_df <- final_df %>%
  select(ResponseId, Category)

# load original dataset
DF <- readRDS(file = here("data/final-data", "globalgratitude_final_cleaned.Rds"))

# remove "no" data quality category
DF_combined <- DF %>%
  left_join(final_df, by = c("ResponseId")) %>%
  filter(Category != "no")

# save csv
write_rds(DF_combined,
  file = here(
    "quality-checks/sensitivity-analyses",
    "QC_globalgratitude_final_cleaned.Rds"
  )
)
```
